model:
  name_or_path: "black-forest-labs/FLUX.1-dev"
  is_flux: true
  quantize: true

train:
  batch_size: 1
  steps: 4000
  gradient_accumulation_steps: 1
  train_unet: true
  train_text_encoder: false
  content_or_style: "balanced"
  gradient_checkpointing: true
  noise_scheduler: "flowmatch"
  optimizer: "adamw8bit"
  lr: 4e-4
  dtype: "bf16"

sample:
  sampler: "flowmatch"
  sample_every: 250
  width: 1024
  height: 1024
  prompts:
    - "woman with red hair, playing chess at the park, bomb going off in the background"
    - "a woman holding a coffee cup, in a beanie, sitting at a cafe"
  guidance_scale: 4
  sample_steps: 20